// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB74e94d9DecodeAnogSrcHandlers(in *jlexer.Lexer, out *loadData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(loadData, 0, 4)
			} else {
				*out = loadData{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 string
			v1 = string(in.String())
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB74e94d9EncodeAnogSrcHandlers(out *jwriter.Writer, in loadData) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			out.String(string(v3))
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v loadData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB74e94d9EncodeAnogSrcHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v loadData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB74e94d9EncodeAnogSrcHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *loadData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB74e94d9DecodeAnogSrcHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *loadData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB74e94d9DecodeAnogSrcHandlers(l, v)
}
